feat and tests : transferTokensERC20
aerius-labs/agar-escrow-contracts pull request #7
Opened 2023-11-02 10:22 UTC by 10priyanshudhiman

ERC20 Transfer Tokens
1. Added transferTokens where escrow can perform transfer
2. Added updateTotalBalance which is used to change the state varible totalBalance which is escrow platfrom balance
3. Added test for transferTokens where escrow does not need to approve to player for transfer as he can directly send them.
4. Added test for if the platform balance is zero or that cantractBalance whose tokens are is zero.

2023-11-07 20:24 UTC, rahulghangas submitted a review, later dismissed

2023-11-08 06:59 UTC, shryasss requested changes
Please do the suggested changes.

2023-11-08 06:59 UTC, shryasss commented on src/EscrowERC20.sol
> +    address public adminAddress = 0x4cd4df5E4485ffd09345bB5dAC0fcE06Dd00ef07;
This should be set in constructor.

2023-11-08 06:59 UTC, shryasss commented on src/EscrowERC20.sol
> +        inEscrAvailable(EscrERC20Available.YES)
remove this

2023-11-08 06:59 UTC, shryasss commented on src/EscrowERC20.sol
> +        public
This should be external.

2023-11-08 06:59 UTC, shryasss commented on src/EscrowERC20.sol
> +        playerAddress = _PlayerAddress;
Use the variables directly instead of assigning to state variables.

2023-11-08 06:59 UTC, shryasss commented on src/EscrowERC20.sol
> +    function updateTotalBalance(uint256 newBalance) public {
Write comments for functions written for test purposes.

2023-11-08 10:20 UTC, shryasss commented on src/EscrowERC20.sol
> +        adminAddress = 0x4cd4df5E4485ffd09345bB5dAC0fcE06Dd00ef07;
Do not hardcode admin address, instead send it as a argument to the constructor.

2023-11-08 10:24 UTC, shryasss requested changes
Requested minor changes

2023-11-08 12:10 UTC, shryasss approved these changes
LGTM

2023-11-12 12:22 UTC, rahulghangas approved these changes

2023-11-12 12:22 UTC, merged