fix :- transfer-nfts
aerius-labs/agar-escrow-contracts pull request #8
Opened 2023-11-03 10:01 UTC by 10priyanshudhiman

Fix- Escrow can approve the players within the contract of ERC721
1. added call where escrow can approve within
2. modify test

2023-11-07 20:24 UTC, rahulghangas submitted a review, later dismissed

2023-11-08 06:34 UTC, shryasss commented on src/EscrowERC20.sol
> +        public
This function should be external if it's only going to be called from outside, i.e if no function inside the Escrow contract is calling this function, then the function should be `external`

2023-11-08 06:38 UTC, shryasss commented on src/EscrowERC20.sol
> +        totalBalance -= _Amount;
It's a good practice to do all the state changes before any external contract calls to prevent re-entrancy. Please transfer the tokens at last.

2023-11-08 06:39 UTC, shryasss commented on src/EscrowERC20.sol
> +        totalBalance -= _Amount;
Also, you should emit an event that tokens were transferred so that backend can listen to these events and update state.

2023-11-08 06:48 UTC, shryasss commented on src/EscrowERC20.sol
> +    modifier onlyEscrow() {
This is not required, please remove this.

2023-11-08 07:01 UTC, shryasss requested changes
Requested changes.

2023-11-08 07:01 UTC, shryasss commented on src/EscrowERC721.sol
> +    address public adminAddress = 0x4cd4df5E4485ffd09345bB5dAC0fcE06Dd00ef07;
To be set in constructor.

2023-11-08 07:01 UTC, shryasss commented on src/EscrowERC721.sol
>          public
Should be `external` and not `public`

2023-11-08 12:09 UTC, shryasss approved these changes, later dismissed
LGTM

2023-11-12 12:23 UTC, rahulghangas approved these changes, later dismissed

2023-11-12 12:23 UTC, merged